### ISSUE TITLE
Continuous-conversion mode outputs the same value

### ISSUE THREAD

**Issue by iamhatesz** [pololu/lis3mdl-arduino#1]
Hi!

I have an issue using LIS3MDL and Arduino library. I compiled and ran your "Serial" example, but instead of getting real-time values I receive the same value of X/Y/Z readings on every loop iteration. When I reset my Arduino, then I get a new value, but just once. I mean:

Serial output:

> X1 Y1 Z1
> X1 Y1 Z1
> ...
> *ARDUINO RESET*
> X2 Y2 Z2
> X2 Y2 Z2
> ...

When I take "mag.enableDefault()" from setup() to loop() and I change "writeReg(CTRL_REG3, 0x00)" to "writeReg(CTRL_REG3, 0x01)" in "void LIS3MDL::enableDefault(void)" then I have a real-time reading, but hey - why should I configure device in the loop? Any ideas?

**Comment by kevin-pololu** [comment]
Hello,
If you are still having trouble with this, please contact us through our normal support channels to continue troubleshooting (https://www.pololu.com/contact). The GitHub issues are intended for tracking development of and bugs in the library code, and this sounds more like a problem with your particular setup or board.

**Comment by kevinjwalters** [comment]
@iamhatesz Did you ever find out what was going on?
