### ISSUE TITLE
how do you convert the values to a compass heading?

### ISSUE THREAD

**Issue by jasperza** [pololu/lis3mdl-arduino#3]
please give an example of how to convert the values to a compass heading, i have tried 

 float Heading = 180*atan2( mag.m.y, mag.m.z)/PI;

but it just gives me a heading from 300 to 200 no matter how the compass is orientated

**Comment by kevin-pololu** [comment]
Hi, jasperza.

Are you using the board "standing up" such that the X axis is pointing into or out of the ground? If so, the Y and Z axes are the right ones to use. However, I'd expect you to actually be using the board lying flat (parallel to the ground), with the Z axis pointing into or out of the ground, in which case you should be using the X and Y axes.

Note that this approach will only work if you do not tilt the magnetometer; to make a tilt-compensated compass, you need an accelerometer as well. In addition, you should make sure you're calibrating the magnetometer to account for the sensor's internal offsets, which are usually quite significant. You can see an example of how to get and use calibration values in the "Calibrate" and "Heading" examples of our [LSM303 library ](https://github.com/pololu/lsm303-arduino) (the LSM303 includes an accelerometer and the Heading example in that library is tilt-compensated, but the magnetometer calibration technique should still apply).

If you continue to have trouble and would like additional help, please post a question on the [Pololu forum](https://forum.pololu.com/), as the GitHub issues are intended for keeping track of problems with and changes to the library itself.

Kevin
